# Generated by Django 3.2.4 on 2021-06-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reservationDetail',
            new_name='reservation_detail',
        ),
    ]
