# Generated by Django 3.2.4 on 2021-06-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_reservationdetail_order_reservation_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='ordered_items',
        ),
    ]
