# Generated by Django 3.2.4 on 2021-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invoice_invoicelineitem_payment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
