# Generated by Django 3.2.4 on 2021-08-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210808_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.orderdetail'),
        ),
    ]
